import type { NextPage } from "next";
import useSWR from "swr";

import Head from "next/head";
import Image from "next/image";
import Layout from "components/Layout";
import Banner from "components/Banner";

import api from "api/instance";

interface FetchProps {
  path: string;
  region: string;
}

const fetcher = (url: string) =>
  api.get(url).then((res) => res.data);

const Home: NextPage = () => {
  const { data, error } = useSWR(["movie/popular", 10], fetcher);

  console.log("data", data, error);
  const imgBackDropList = data?.results?.slice(0, 10) || [];
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner imgBackDropList={imgBackDropList} />
    </Layout>
  );
};

export default Home;
